version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: restaurant_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-restaurant_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  app:
    build: .
    container_name: restaurant_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
      echo 'Waiting for database to be ready...' &&
      until alembic upgrade head; do
        echo 'Alembic upgrade failed, retrying in 5 seconds...'
        sleep 5
      done &&
      echo 'Database migration complete, starting Uvicorn...' &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic

volumes:
  postgres_data:
